// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppService.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Generated.Protobuf {
  /// <summary>
  /// ------------- SERVICE -------------
  /// </summary>
  public static partial class AppService
  {
    static readonly string __ServiceName = "AppService";

    static readonly grpc::Marshaller<global::Generated.Protobuf.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Generated.Protobuf.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Generated.Protobuf.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Generated.Protobuf.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::Generated.Protobuf.Request, global::Generated.Protobuf.Response> __Method_sendRequest = new grpc::Method<global::Generated.Protobuf.Request, global::Generated.Protobuf.Response>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "sendRequest",
        __Marshaller_Request,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Generated.Protobuf.AppServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AppService</summary>
    public abstract partial class AppServiceBase
    {
      public virtual global::System.Threading.Tasks.Task sendRequest(grpc::IAsyncStreamReader<global::Generated.Protobuf.Request> requestStream, grpc::IServerStreamWriter<global::Generated.Protobuf.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AppService</summary>
    public partial class AppServiceClient : grpc::ClientBase<AppServiceClient>
    {
      /// <summary>Creates a new client for AppService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AppServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AppService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AppServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AppServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AppServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Generated.Protobuf.Request, global::Generated.Protobuf.Response> sendRequest(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return sendRequest(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Generated.Protobuf.Request, global::Generated.Protobuf.Response> sendRequest(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_sendRequest, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AppServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AppServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AppServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sendRequest, serviceImpl.sendRequest).Build();
    }

  }
}
#endregion
